{ config, pkgs, lib, inputs, ... }:
with lib;
let
  # Shorter name to access final settings a
  # user of hello.nix module HAS ACTUALLY SET.
  # cfg is a typical convention.
  inherit (lib) mkOption mkEnableOption types mkIf;
  inherit (types) path str bool listOf;
  option = config.module.hyprland;
  toggleWindowScript = pkgs.writeScript "toggle-window.sh" ''
    #!/usr/bin/env bash
    pgrep fuzzel && pkill fuzzel && exit 0
    if hyprctl clients | grep -q "toggle-window"; then
        hyprctl dispatch closewindow class:toggle-window
    else
        alacritty --class=toggle-window -e bash -c "$@"
    fi
  '';
  toggleMenu = pkgs.writeScript "toggle-menu.sh" ''
    #!/usr/bin/env bash
    pgrep fuzzel && pkill fuzzel && exit 0
    if hyprctl clients | grep -q "toggle-window"; then
        hyprctl dispatch closewindow class:toggle-window
    else
        fuzzel
    fi
  '';
  parseHotkeysScript = pkgs.writeScript "parseHotkeys.sh" ''
    #!/usr/bin/env bash

    hyprctl binds -j | jq -r '
      .[] |
      .description as $desc |
      .key as $key |
      .modmask as $mask |
      .dispatcher as $dispatcher |
      .arg as $arg |

      (
        (if $desc == "" then "<no description>" else $desc end) as $dsc |
        (
          (
            (
              (if ($mask / 1) % 2    >= 1 then ["Shift"] else [] end) +
              (if ($mask / 2) % 2    >= 1 then ["Lock"]  else [] end) +
              (if ($mask / 4) % 2    >= 1 then ["Mod1"]  else [] end) +
              (if ($mask / 8) % 2    >= 1 then ["Ctrl"]  else [] end) +
              (if ($mask / 16) % 2   >= 1 then ["Mod3"]  else [] end) +
              (if ($mask / 32) % 2   >= 1 then ["Mod5"]  else [] end) +
              (if ($mask / 64) % 2   >= 1 then ["Super"]  else [] end)
            ) | join("+")
          ) + (if $key != "" then "+" + $key else "" end) as $hotkey |

          [$dsc, $hotkey, ($dispatcher + " " + $arg)]
        )
      ) | @tsv
    ' | awk -F'\t' '{
      desc = sprintf("%-50s", $1)
      key  = sprintf("%-25s", $2)
      cmd  = (length($3) > 50) ? substr($3, 1, 47) "..." : $3
      printf "%s    %s    %s\n", desc, key, cmd
    }'
  '';
in {
  imports = [
    # Paths to other modules.
    # Compose this module out of smaller ones.
  ];

  options.module.hyprland = {
    # Option declarations.
    # Declare what settings a user of this module module can set.
    # Usually this includes a global "enable" option which defaults to false.
    enable = mkEnableOption "hyprland";
    startup-commands = mkOption {
      type = listOf str;
      default = [ ];
    };
    monitors = {
      left = {
        enable = mkOption {
          type = bool;
          default = false;
        };
        name = mkOption {
          type = str;
          description = "Left monitor";
          default = "";
        };
        settings = mkOption {
          type = str;
          description = "Settings for monitor, e.g. 2560x1440@144,0x0,1.0";
          default = "preferred,0x0,1.0";
        };
      };
      middle = {
        enable = mkOption {
          type = bool;
          default = false;
        };
        name = mkOption {
          type = str;
          description = "Middle monitor";
          default = "DP-3";
        };
        settings = mkOption {
          type = str;
          description = "Settings for monitor, e.g. 2560x1440@144,0x0,1.0";
          default = "preferred,0x0,1.0";
        };
      };
      right = {
        enable = mkOption {
          type = bool;
          default = false;
        };
        name = mkOption {
          type = str;
          description = "Right monitor";
          default = "HDMI-A-2";
        };
        settings = mkOption {
          type = str;
          description = "Settings for monitor, e.g. 2560x1440@144,0x0,1.0";
          default = "preferred,2560x0,1.0";
        };
      };
    };
  };

  config = mkIf option.enable {
    #nn Option definitions.
    # Define what other settings, services and resources should be active.
    # Usually these depend on whether a user of this module chose to "enable" it
    # using the "option" above.
    # Options for modules imported in "imports" can be set here.
    home.file = {
      ".config/wofi/print-command-config" = {

        text = ''
          # Generated by Home Manager.
          allow_images=true
          allow_markup=true
          content_halign=fill
          filter_rate=100
          gtk_dark=true
          halign=fill
          height=400
          image_size=28
          insensitive=true
          location=center
          orientation=vertical
          show=drun
          text=Search...
          width=800
          print_command=true
          	'';
      };
    };
    home.pointerCursor = {
      # gtk.enable = true;
      # x11.enable = true;
      package = pkgs.bibata-cursors;
      name = "Bibata-Modern-Classic";
      size = 16;
    };

    gtk = {
      enable = true;
      theme = {
        package = pkgs.flat-remix-gtk;
        name = "Flat-Remix-GTK-Grey-Darkest";
      };
      iconTheme = {
        package = pkgs.adwaita-icon-theme;
        name = "Adwaita";
      };

      font = {
        name = "Sans";
        size = 11;
      };
    };

    wayland.windowManager.hyprland = {
      enable = true;
      sourceFirst = true;
      systemd.enable = true;
      xwayland.enable = true;
      package =
        inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
      settings = {
        exec-once = option.startup-commands;
        monitor = mkMerge [
          (mkIf (option.monitors.left.enable)
            [ "${option.monitors.left.name},${option.monitors.left.settings}" ])
          (mkIf (option.monitors.middle.enable) [
            "${option.monitors.middle.name},${option.monitors.middle.settings}"
          ])
          (mkIf (option.monitors.right.enable) [
            "${option.monitors.right.name},${option.monitors.right.settings}"
          ])
          ([ "Unknown-1,disable" ])
        ];
        ecosystem.no_update_news = true;
        debug.disable_logs = false;
        "$terminal" = "alacritty";
        "$menu" = "fuzzel";
        "$monitor-1" = "${option.monitors.left.name}";
        "$monitor-2" = "${option.monitors.middle.name}";
        "$monitor-3" = "${option.monitors.right.name}";
        "$mainMod" = "SUPER";

        "$browserRegexp" = "firefox|Chromium|Vivaldi-stable";
        "$chatRegexp" = "discord|vesktop|Slack";
        "$terminalRegexp" = "Alacritty";
        "$productivityRegexp" = "everdo";
        "$musicRegexp" = ".*Spotify.*";
        "$gamingRegexp" = "steam";
        "$settingsRegexp" = "com.saivert.pwvucontrol";
        "$programmingRegexp" = "code-url-handler|jetbrains-rider|Godot";
        windowrulev2 = [
          "suppressevent maximize center, class:.*"
          "tag +setting,class:$settingsRegexp"
          "tag +music,title:$musicRegexp"
          "tag +gaming,class:$gamingRegexp"
          "tag +productivity,class:$productivityRegexp"
          "tag +chat,class:$chatRegexp"
          "tag +coding,class:$programmingRegexp"
          "tag +term,class:$terminalRegexp"
          "tag +browser,class:$browserRegexp"
          "workspace 1 silent,tag:setting"
          "workspace 2 silent,tag:music"
          "workspace 3 silent,tag:gaming"
          "workspace 5 silent,tag:productivity"
          "workspace 6 silent,tag:chat"
          "workspace 7 silent,tag:coding"
          "workspace 8 silent,tag:term"
          "workspace 9 silent,tag:browser"
          "float,class:toggle-window"
          "pin,class:toggle-window"
          "size 75% 75%,class:toggle-window"

        ];
        general = {
          gaps_in = 5;
          gaps_out = 20;
          border_size = 2;
          "col.active_border" = "rgba(33ccffee) rgba(00ff99ee) 45deg";
          "col.inactive_border" = "rgba(595959aa)";
          resize_on_border = false;
          allow_tearing = false;
          layout = "master";
        };

        #render = {
        # explicit_sync = 0;
        #  explicit_sync_kms = 0;
        #};

        cursor = { no_hardware_cursors = true; };

        decoration = {
          rounding = 10;
          active_opacity = 1.0;
          inactive_opacity = 1.0;

          blur = {
            enabled = true;
            size = 3;
            passes = 1;
            vibrancy = 0.1696;
          };
        };

        animations = {
          enabled = true;
          bezier = "myBezier, 0.05, 0.9, 0.1, 1.05";
          animation = [
            "windows, 1, 3, myBezier"
            "windowsOut, 1, 3, default, popin 80%"
            "border, 1, 1, default"
            "borderangle, 1, 3, default"
            "fade, 1, 1, default"
            "workspaces, 1, 3, default"
          ];
        };

        master = { new_status = "master"; };

        misc = {
          force_default_wallpaper = 0;
          disable_hyprland_logo = false;
        };

        input = {
          kb_layout = "se";
          kb_variant = "";
          kb_model = "";
          kb_options = "";
          kb_rules = "";
          follow_mouse = 2;
          float_switch_override_focus = 0;
          sensitivity = 0; # -1.0 - 1.0, 0 means no modification.

          touchpad = { natural_scroll = false; };
        };

        # https://wiki.hyprland.org/Configuring/Variables/#gestures
        gestures = { workspace_swipe = false; };

        env = [
          "LIBVA_DRIVER_NAME,nvidia"
          "XDG_SESSION_TYPE,wayland"
          "__GLX_VENDOR_LIBRARY_NAME,nvidia"
          "XCURSOR_SIZE,24"
          "HYPRCURSOR_SIZE,24"
        ];
        bindd = [
          "$mainMod, I, Remove master, layoutmsg, removemaster"
          "$mainMod, O, Add master, layoutmsg, addmaster"
          "$mainMod, space, Launch terminal, exec, $terminal"
          "$mainMod ALT, space, Execute command, exec, [workspace unset] $terminal"
          "$mainMod, C, Kill active window, killactive,"
          "$mainMod, F12, Exit Hyprland, exit,"
          "$mainMod, F, Open file manager, exec, $fileManager"
          "$mainMod SHIFT, F, Toggle floating, togglefloating,"
          "$mainMod, D, Toggle menu, exec, ${toggleMenu}"
          "$mainMod, escape, Toggle window, exec, ${toggleWindowScript} :;"
          "$mainMod, B, Toggle Bluetooth, exec, ${toggleWindowScript} bluetuith"
          "$mainMod, s, Toggle Spotify player, exec, ${toggleWindowScript} spotify_player"
          "$mainMod, V, Toggle Pulse audio mixer, exec, ${toggleWindowScript} pulsemixer"
          "$mainMod, P, Toggle htop, exec, ${toggleWindowScript} htop"
          "$mainMod, G, Toggle ChatGPT, exec, ${toggleWindowScript} chatgpt"
          ''
            $mainMod, H, Toggle window, exec, ${toggleWindowScript} "${parseHotkeysScript} | fzf"''
          ''
            $mainMod, F7, Take screenshot, exec, grim -g "$(slurp)" - | swappy -f -''
          "$mainMod ALT, D, Execute command, exec, bash -c"
          "$mainMod, P, Toggle pseudo mode, pseudo, # dwindle"
          "$mainMod, A, Toggle fullscreen, fullscreen, 2"
          "$mainMod, code:69, Focus monitor $monitor-1, focusmonitor, $monitor-1"
          "$mainMod, code:70, Focus monitor $monitor-2, focusmonitor, $monitor-2"
          "$mainMod, code:71, Focus monitor $monitor-3, focusmonitor, $monitor-3"
          "$mainMod SHIFT, left, Move window l, movewindow, l"
          "$mainMod SHIFT, right, Move window r, movewindow, r"
          "$mainMod SHIFT, up, Move window u, movewindow, u"
          "$mainMod SHIFT, down, Move window d, movewindow, d"
          "$mainMod, left, Move focus l, movefocus, l"
          "$mainMod, right, Move focus r, movefocus, r"
          "$mainMod, up, Move focus u, movefocus, u"
          "$mainMod, down, Move focus d, movefocus, d"
          "$mainMod ALT, 1, Toggle special WS 1, togglespecialworkspace, 1"
          "$mainMod ALT, 2, Toggle special WS 2, togglespecialworkspace, 2"
          "$mainMod ALT, 3, Toggle special WS 3, togglespecialworkspace, 3"
          "$mainMod ALT, 4, Toggle special WS 4, togglespecialworkspace, 4"
          "$mainMod ALT, 5, Toggle special WS 5, togglespecialworkspace, 5"
          "$mainMod ALT, 6, Toggle special WS 6, togglespecialworkspace, 6"
          "$mainMod ALT, 7, Toggle special WS 7, togglespecialworkspace, 7"
          "$mainMod ALT, 8, Toggle special WS 8, togglespecialworkspace, 8"
          "$mainMod ALT, 9, Toggle special WS 9, togglespecialworkspace, 9"
          "$mainMod ALT, 0, Toggle special WS 0, togglespecialworkspace, 0"
          "$mainMod ALT CTRL, 1, Move to WS special:1, movetoworkspace, special:1"
          "$mainMod ALT CTRL, 2, Move to WS special:2, movetoworkspace, special:2"
          "$mainMod ALT CTRL, 3, Move to WS special:3, movetoworkspace, special:3"
          "$mainMod ALT CTRL, 4, Move to WS special:4, movetoworkspace, special:4"
          "$mainMod ALT CTRL, 5, Move to WS special:5, movetoworkspace, special:5"
          "$mainMod ALT CTRL, 6, Move to WS special:6, movetoworkspace, special:6"
          "$mainMod ALT CTRL, 7, Move to WS special:7, movetoworkspace, special:7"
          "$mainMod ALT CTRL, 8, Move to WS special:8, movetoworkspace, special:8"
          "$mainMod ALT CTRL, 9, Move to WS special:9, movetoworkspace, special:9"
          "$mainMod ALT CTRL, 0, Move to WS special:0, movetoworkspace, special:0"
          "$mainMod, 1, Focus WS 1 on current monitor, focusworkspaceoncurrentmonitor, 1"
          "$mainMod, 2, Focus WS 2 on current monitor, focusworkspaceoncurrentmonitor, 2"
          "$mainMod, 3, Focus WS 3 on current monitor, focusworkspaceoncurrentmonitor, 3"
          "$mainMod, 4, Focus WS 4 on current monitor, focusworkspaceoncurrentmonitor, 4"
          "$mainMod, 5, Focus WS 5 on current monitor, focusworkspaceoncurrentmonitor, 5"
          "$mainMod, 6, Focus WS 6 on current monitor, focusworkspaceoncurrentmonitor, 6"
          "$mainMod, 7, Focus WS 7 on current monitor, focusworkspaceoncurrentmonitor, 7"
          "$mainMod, 8, Focus WS 8 on current monitor, focusworkspaceoncurrentmonitor, 8"
          "$mainMod, 9, Focus WS 9 on current monitor, focusworkspaceoncurrentmonitor, 9"
          "$mainMod, 0, Focus WS 10 on current monitor, focusworkspaceoncurrentmonitor, 10"
          "$mainMod CTRL, 1, Move to WS 1, movetoworkspacesilent, 1"
          "$mainMod CTRL, 2, Move to WS 2, movetoworkspacesilent, 2"
          "$mainMod CTRL, 3, Move to WS 3, movetoworkspacesilent, 3"
          "$mainMod CTRL, 4, Move to WS 4, movetoworkspacesilent, 4"
          "$mainMod CTRL, 5, Move to WS 5, movetoworkspacesilent, 5"
          "$mainMod CTRL, 6, Move to WS 6, movetoworkspacesilent, 6"
          "$mainMod CTRL, 7, Move to WS 7, movetoworkspacesilent, 7"
          "$mainMod CTRL, 8, Move to WS 8, movetoworkspacesilent, 8"
          "$mainMod CTRL, 9, Move to WS 9, movetoworkspacesilent, 9"
          "$mainMod CTRL, 0, Move to WS 10, movetoworkspacesilent, 10"
          "$mainMod SHIFT, 1, Focus WS 12 on current monitor, focusworkspaceoncurrentmonitor, 12"
          "$mainMod SHIFT, 2, Focus WS 22 on current monitor, focusworkspaceoncurrentmonitor, 22"
          "$mainMod SHIFT, 3, Focus WS 32 on current monitor, focusworkspaceoncurrentmonitor, 32"
          "$mainMod SHIFT, 4, Focus WS 42 on current monitor, focusworkspaceoncurrentmonitor, 42"
          "$mainMod SHIFT, 5, Focus WS 52 on current monitor, focusworkspaceoncurrentmonitor, 52"
          "$mainMod SHIFT, 6, Focus WS 62 on current monitor, focusworkspaceoncurrentmonitor, 62"
          "$mainMod SHIFT, 7, Focus WS 72 on current monitor, focusworkspaceoncurrentmonitor, 72"
          "$mainMod SHIFT, 8, Focus WS 82 on current monitor, focusworkspaceoncurrentmonitor, 82"
          "$mainMod SHIFT, 9, Focus WS 92 on current monitor, focusworkspaceoncurrentmonitor, 92"
          "$mainMod SHIFT, 0, Move to WS 102 on current monitor, focusworkspaceoncurrentmonitor, 102"
          "$mainMod SHIFT CTRL, 1, Move to WS 12 on current monitor, movetoworkspace, 12"
          "$mainMod SHIFT CTRL, 2, Move to WS 22 on current monitor, movetoworkspace, 22"
          "$mainMod SHIFT CTRL, 3, Move to WS 32 on current monitor, movetoworkspace, 32"
          "$mainMod SHIFT CTRL, 4, Move to WS 42 on current monitor, movetoworkspace, 42"
          "$mainMod SHIFT CTRL, 5, Move to WS 52 on current monitor, movetoworkspace, 52"
          "$mainMod SHIFT CTRL, 6, Move to WS 62 on current monitor, movetoworkspace, 62"
          "$mainMod SHIFT CTRL, 7, Move to WS 72 on current monitor, movetoworkspace, 72"
          "$mainMod SHIFT CTRL, 8, Move to WS 82 on current monitor, movetoworkspace, 82"
          "$mainMod SHIFT CTRL, 9, Move to WS 92 on current monitor, movetoworkspace, 92"
          "$mainMod SHIFT CTRL, 0, Move to WS 102 on current monitor, movetoworkspace, 102"
          "$mainMod SHIFT CTRL, C, Execute command, exec, bash -c"
        ];
        bindm = [
          "$mainMod, mouse:272, movewindow"
          "$mainMod, mouse:273, resizewindow"
        ];
      };
    };
    programs.hyprlock.enable = true;
    services = {
      hypridle.enable = false;
      hyprpaper.enable = false;
    };
  };
}
